latteart-org/latteart-repository

externals/package.json
package.json
yarn.lock

fix jsdoc version

---

.gitignore
.prettierignore
package.json

add dummy file to imports directory

---

package.json

release v2.1.1

---

src/services/TestResultService.ts
src/services/TimestampService.ts
tests/helper/createServiceMock.ts
tests/unit/services/NotesService.spec.ts
tests/unit/services/ProjectsService.spec.ts
tests/unit/services/TestResultService.spec.ts
tests/unit/services/TestStepService.spec.ts

latteart-org/latteart#25 timestamp refactoring

---

src/interfaces/TestResults.ts
src/lib/deserializeTestResult.ts
src/services/ExportService.ts
src/services/TestResultService.ts

fix latteart-org/latteart#58 import starttimestamp

---

src/interfaces/TestResults.ts
src/routes/routes.ts
src/services/TestResultService.ts

fix latteart-org/latteart#36 modify createTestResult method

---

src/interfaces/Sessions.ts
src/routes/routes.ts

fix latteart-org/latteart#70 modify testResultFiles

---

src/interfaces/Sessions.ts
src/routes/routes.ts

fix latteart-org/latteart#74 option menu

---

src/controllers/TestResultImportController.ts
src/lib/Request.ts

fix latteart-org/latteart#69 automatically create temp directory.

---

src/controllers/ProjectImportController.ts
src/interfaces/ProjectImport.ts
src/routes/routes.ts
src/services/ProjectImportService.ts

fix latteart-org/latteart#69 import project to remote.

---

src/interfaces/DeviceConfigs.ts
src/lib/settings/Constants.ts
src/lib/settings/SettingsEnum.ts

fix latteart-org/latteart#46 edge compatible

---

externals/package.json
externals/yarn.lock
package.json
yarn.lock

fix package error

---

src/controllers/TestResultImportController.ts
src/lib/Request.ts
src/services/ExportFileRepositoryService.ts

fix latteart-org/latteart#191 change export file name

---

package-lock.json
src/ServerError.ts
src/controllers/ScreenshotsController.ts
src/routes/routes.ts
src/services/ScreenshotsService.ts
src/services/StaticDirectoryService.ts
tests/helper/createServiceMock.ts
tests/unit/services/ImageFileRepositoryService.spec.ts
tests/unit/services/ScreenshotsService.spec.ts

fix latteart-org/latteart#21 add screenshots download

---

src/services/TestResultService.ts

fix latteart-org/latteart#320 foreign key constraint failed

---

src/entities/SessionEntity.ts
src/index.ts
src/migrations/1656305325919-UpdateSessionEntity.ts

fix latteart-org/latteart#313 delete empty test result

---

src/interfaces/Projects.ts
src/services/ProjectsService.ts
src/services/SnapshotFileRepositoryService.ts

fix latteart-org/latteart#316 modify issue dialog imagefile

---

src/TransactionRunner.ts

fixed not to lock when transaction fails

fix latteart-org/latteart#323 fix transaction lock

---

jest.config.js

exclusion settings for jest

---

src/services/ProjectsService.ts

fix latteart-org/latteart#48 sort snapshot issues

---

src/services/TestTargetsService.ts

fix latteart-org/latteart#373 test progress insertion

---

src/controllers/ProjectExportController.ts
src/services/ExportFileRepositoryService.ts
src/services/ProjectExportService.ts
src/services/ProjectImportService.ts
tests/unit/services/ProjectExportService.spec.ts
tests/unit/services/ProjectImportService.spec.ts

fix latteart-org/latteart#375 modify project import and  export

---

src/controllers/ProjectTestScriptsController.ts
src/controllers/TestScriptsController.ts
src/interfaces/TestScripts.ts
src/lib/scriptGenerator/TestScriptGenerator.ts
src/lib/scriptGenerator/codeGenerator/TestScriptCodeGeneratorFactory.ts
src/lib/scriptGenerator/codeGenerator/js/testSuite/JSTestSuiteCodeGenerator.ts
src/lib/scriptGenerator/model/TestScriptModelGeneratorFactory.ts
src/routes/routes.ts
src/services/TestScriptsService.ts
tests/unit/lib/scriptGenerator/codeGenerator/js/testSuite/JSTestSuiteCodeGenerator.spec.ts
tests/unit/services/TestScriptsService.spec.ts

latteart-org/latteart#361 modify script generation api option

---

src/ServerError.ts
src/controllers/SessionsController.ts
src/controllers/StoriesController.ts
src/interfaces/Sessions.ts
src/interfaces/Stories.ts
src/lib/entityToResponse.ts
src/routes/routes.ts
src/services/ProjectsService.ts
src/services/SessionsService.ts
src/services/StoriesService.ts
tests/unit/services/SessionService.spec.ts

divide project api

---

.gitignore
package.json
src/controllers/ProjectImportController.ts
src/controllers/TestResultImportController.ts
src/interfaces/ProjectImport.ts
src/interfaces/TesResultImport.ts
src/routes/routes.ts
src/services/ImportFileRepositoryService.ts
src/services/ImportService.ts
src/services/ProjectImportService.ts
tests/unit/services/ProjectImportService.spec.ts

import via file api

---

src/lib/FileArchiver.ts

fix latteart-org/latteart#397 fix zip file writing

---

latteart.config.json
src/controllers/ConfigsController.ts
src/interfaces/Configs.ts
src/lib/settings/Settings.ts
src/lib/settings/SettingsProvider.ts
src/routes/routes.ts
src/services/ConfigsService.ts
tests/resources/latteart.config.json
tests/unit/SettingsProvider.spec.ts
tests/unit/lib/SettingsProvider.spec.ts

latteart-org/latteart#421 modify autofill settings

---

src/services/TestResultImportService.ts

fix latteart-org/latteart#432 fix start timestamp import

---

src/services/SessionsService.ts

latteart-org/latteart#430 modify update testingTime

---

src/lib/entityToResponse.ts

fix latteart-org/latteart#413 fix order of snapshot issues

---

src/lib/settings/Settings.ts
src/routes/routes.ts

latteart-org/latteart#440, latteart-org/latteart#441 change operator 'regex' to 'contains'

---

externals/package.json
externals/yarn.lock
package.json
yarn.lock

latteart-org/latteart#461 upgrade dependencies

---

package.json
yarn.lock

latteart-org/latteart#461 fix routes generation

---

src/ServerError.ts
src/controllers/ConfigExportController.ts
src/interfaces/Configs.ts
src/routes/routes.ts
src/services/ConfigExportService.ts

fix latterart-org/latteart#464 add config export.

---

src/controllers/ConfigExportController.ts

fix latteart-org/latteart#464 change export directory.

---

src/services/ConfigExportService.ts

latteart-org/latteart#464 rename config file.

---

src/lib/entityToResponse.ts

fix latteart-org/latteart#502 sort sessions

---

src/services/TestProgressService.ts
src/services/TestTargetsService.ts

fix latteart-org/latteart#468 fix register test progresses

---

src/controllers/SnapshotsController.ts
src/interfaces/Configs.ts
src/routes/routes.ts
src/services/SnapshotFileRepositoryService.ts
src/services/SnapshotsService.ts

fix latteart-org/latteart#547 modify snapshot locale

---

src/services/TestProgressService.ts

fix latteart-org/latteart#468, fix latteart-org/latteart#469 fix testprogress save error

---

src/controllers/ConfigsController.ts
src/interfaces/Configs.ts
src/lib/settings/settingsConverter.ts
src/routes/routes.ts
src/services/ConfigExportService.ts
src/services/ConfigsService.ts
src/services/SnapshotFileRepositoryService.ts

fix latteart-org/latteart#555 refactor config

---

src/services/TestResultService.ts

fix latteart-org/latteart#559 fix delete testresult

---

src/controllers/TestResultsController.ts
src/interfaces/Sessions.ts
src/routes/routes.ts
src/services/SessionsService.ts

fix latteart-org/latteart#562 fix delete testresult dialog

---

src/ServerError.ts
src/controllers/TestResultsController.ts
src/interfaces/TestResults.ts
src/interfaces/TestScripts.ts
src/routes/routes.ts
src/services/TestResultService.ts
tests/helper/createServiceMock.ts
tests/unit/services/IssueReportService.spec.ts
tests/unit/services/ProjectExportService.spec.ts
tests/unit/services/TestScriptsService.spec.ts

latteart-org/latteart#358 sequence view via api

---

src/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.spec.ts

fix latteart-org/latteart#582 generate code to click i tag element

---

src/lib/elementLocator.ts
tests/unit/lib/LocatorGenerator.spec.ts

fix latteart-org/latteart#602 fixed not to use HTML encode in locators

---

src/ServerError.ts
src/controllers/StoriesController.ts
src/interfaces/Stories.ts
src/routes/routes.ts
src/services/StoriesService.ts

improve display performance of management tool

---

src/interfaces/TestScripts.ts
src/lib/scriptGenerator/TestScriptGenerator.ts
src/lib/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectCodeGenerator.ts
src/lib/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectMethodCommentGenerator.ts
src/lib/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.ts
src/lib/scriptGenerator/codeGenerator/js/pageObject/JSSimplePageObjectCodeGenerator.ts
src/lib/scriptGenerator/model/TestScriptModelGeneratorFactory.ts
src/lib/scriptGenerator/model/pageObject/method/operation/FormalArgumentsCollector.ts
src/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.ts
src/lib/scriptGenerator/model/pageObject/method/operation/PageObjectOperation.ts
src/lib/scriptGenerator/model/pageObject/method/operation/UnnecessaryOperationFilter.ts
src/lib/scriptGenerator/model/testSuite/InputGroupCollector.ts
src/routes/routes.ts
src/services/TestScriptsService.ts
tests/unit/lib/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectCodeGenerator.spec.ts
tests/unit/lib/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.spec.ts
tests/unit/lib/scriptGenerator/codeGenerator/js/pageObject/JSSimplePageObjectCodeGenerator.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/PageObject.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/IncludedMethodFilter.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/PageObjectMethod.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/DuplicateElementOperationFilter.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/FormalArgumentsCollector.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/PageObjectOperationFactory.spec.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/UnnecessaryOperationFilter.spec.ts
tests/unit/lib/scriptGenerator/model/testSuite/InputGroupCollector.spec.ts
tests/unit/services/TestScriptsService.spec.ts

latteart-org/latteart#607 add custom button definition for test script

---

src/lib/elementLocator.ts
src/services/TestScriptsService.ts
tests/unit/lib/LocatorGenerator.spec.ts

fix latteart-org/latteart#580 fix Locator used in PageObject not working as intended

---

src/interfaces/TestScripts.ts
src/lib/scriptGenerator/TestScriptGenerator.ts
src/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.ts
src/routes/routes.ts
tests/unit/lib/scriptGenerator/model/pageObject/method/operation/PageObjectElementFactory.spec.ts

latteart-org/latteart#607 fix interface
